# Generated by Django 4.2.13 on 2024-06-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateField(auto_now_add=True)),
                ('atualizacao', models.DateField(auto_now=True)),
                ('titulo', models.CharField(max_length=255)),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('descricao', models.TextField(blank=True, default='')),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
            },
        ),
    ]
